# Сообщение, которое получает игрок при отсутствии проходки
kick-message: "§cУ вас нету проходки на этот сервер!§b Купить её можно на сайте Texonia.su"

# Список игроков с проходкой
players:
# Пример:
# EminGame5392: true